### ISSUE TITLE
Where is the pre-processor?

### ISSUE THREAD

**Issue by annadapb** [jhellingman/oriya-tex#2]
In the manual (orman.ps), there is a mention of a pre-processor that takes `<OR> </OR>` macros to transcribe texts to TeX macros. I assume, it converts say, `k++ra` to `k\orsecra`. This will indeed make it much easier to type Oriya. However, I cannot find the pre-processor in this repo. In the [CTAN repo](https://ctan.org/pkg/oriya), the oriya package has a `oriya.c` file in the `/bin` directory. Assuming that is the pre-processor, first it doesn't compile with modern C standard. It only compiles with `-std=c99` flag with GCC (on Linux).

And the pre-processor doesn't work. For example, running the pre-processor on the file `/docs/kathamaala.or` returns the same exact text back. Can you please point me to the legit version of the pre-processor? Thank you.

**Comment by jhellingman** [comment]
I've never completed the pre-processor, and since nowadays, support for Oriya script is widely available, I have no intention to do so. This archive is only available for historical interest (I made those designs back in 1995).
